### ISSUE TITLE
Replace return_variable_types with return_types to use ColumnSchema

### ISSUE THREAD

**Issue by gsheni** [alteryx/featuretools#1264]
- The woodwork integration means that `return_types` should now be the parameter, which takes in ColumnSchema
- The CFM/DFS logic will need to be updated as well.

**Comment by thehomebrewnerd** [comment]
@gsheni Regarding this issue and #1265 - since primitive input/output types are now defined in terms of a `ColumnSchema` that defines the logical type or semantic tag or both, do we want to carry that behavior over here instead of separating these into two return parameters?

Should this be something like `return_types` instead of `return_logical_types` and `return_semantic_tags`? 

With this approach, if a user wanted a specific semantic tag, they could specify `ColumnSchema(semantic_tags={'numeric'})`. If they wanted a specific logical type, it would be `ColumnSchema(logical_type=Double)` and if they wanted to match both it would be something like `ColumnSchema(logical_type=Double, semantic_tags={'numeric'})`

**Comment by gsheni** [comment]
@thehomebrewnerd `return_types` with ColumnSchema is the right approach here.

**Comment by thehomebrewnerd** [comment]
Closed by #1523
