### ISSUE TITLE
Memory crashing when using featuretools/dask

### ISSUE THREAD

**Issue by gautambak** [alteryx/featuretools#1357]
I'm not sure what I'm doing wrong, but basically I'm taking a fairly large dataframe(11GB) and converting it to dask before running featuretools on it. During DFS my system is running out of memory, which is strange to me because I thought it should be writing to disk?

```
from dask.distributed import Client, progress

client = Client(n_workers=2, threads_per_worker=2, memory_limit='2GB')
client

import featuretools as ft
import dask.dataframe as dd
dt = {}
dt.update(dict.fromkeys(catgoricalValues, ft.variable_types.Categorical))
dt.update(dict.fromkeys(NumericColumns, ft.variable_types.Numeric))
dask_df = dd.from_pandas(Main[NumericColumns + catgoricalValues], npartitions=50000)
dask_df  # this works

# Make an entityset and add the entity
es = ft.EntitySet(id = 'Test')
es = es.entity_from_dataframe(entity_id="dask_entity", dataframe=dask_df, make_index = True, index="index", variable_types=dt)

# primatives to use
default_agg_primitives =  ["sum", "std", "max", "min", "mean", "count", "percent_true", "num_unique"]
default_trans_primitives =  ["add_numeric", 'multiply_numeric']

feature_matrix, feature_defs = ft.dfs(entityset = es, target_entity = 'dask_entity',
                                       trans_primitives = default_trans_primitives,
                                       agg_primitives=default_agg_primitives, 
                                        max_depth = 2, features_only=False, verbose = True)
```

My session crashes at this point from using all the memory. I followed various tutorials but I'm not sure what I'm doing wrong? My goal is after DFS is done, I would save the results to a file that I can then pass on to TF/Keras.

**Comment by thehomebrewnerd** [comment]
I've run into memory issues at times as well with large Dask dataframes. Just curious about the number of columns in your original dataframe versus the number of new feature columns that are being generated. One issue I have seen is that because we are potentially adding a lot of new columns to each partition, the partition sizes can grow large if the feature matrix has a lot of columns.

With that I have a few questions that might help narrow down what is going on:
- Is the failure happening when you call `ft.dfs` or after that when you try to save the results to disk?
- How many columns are present in `dask_df`?
- How many features are being generated in your call to `ft.dfs`? If needed you can get the features without computing them by setting `features_only=True` when you call `ft.dfs`
- Are you able to generate a feature matrix successfully if you use fewer features, or if you set max_depth to 1?

**Comment by gautambak** [comment]
Thank you @thehomebrewnerd !

To answer your questions. For this test, here are details:
1. dataframe shape is (5926577, 163)
2. How can I find out the number of features being generated? I basically pass that dataframe to dask and then it crashes.
3. You are the correct, it's crashing when I'm calling ft.dfs. I don't even have the chance to save it to disk?
4. columns for dask should be the same as above? Maybe reduced by 2.
5. If I setup max_depth=1 I get a error 'ValueError: too many values to unpack (expected 2)'
6. I reduced the columns to 112 and still got the too many values to unpack error
7. when I reduce the column size and change max_depth back to 2, I get the same issue where it runs out of memory.

Random question but if the memory keeps expanding then it makes sense why I would get memory errors before the app crashes. Does it mean I have to make smaller partitions? Right now I'm creating 50k partitions with memory set to 2GB for 2 works on dask.

**Comment by gautambak** [comment]
This morning I tried to reduce the agg_primatives to just sum & std and kept trans primatives to add_numeric, multiply_numeric with these settings:
```
default_agg_primitives =  ["sum", "std"]
default_trans_primitives =  ["add_numeric", 'multiply_numeric']
feature_matrix, feature_defs = ft.dfs(entityset = es, target_entity = 'dask_entity',
                                       trans_primitives = default_trans_primitives,
                                       agg_primitives=default_agg_primitives, 
                                        max_depth=2, features_only=False, verbose = True)
```

it took a while(~30 min to get started but eventually I saw a progress bar and it was completed) but when I tried to view the results via - ```feature_matrix.head()``` It kept getting memory budget warnings.

I killed the process and tried to instead save it to a file to view later and then my app crashed due to running out of memory 
```feature_matrix.to_parquet("./test.parquet", engine='auto')```

**Comment by thehomebrewnerd** [comment]
@gautambak Thanks for the update. I'll look at this in more detail today.

In the last run you just did, when you saw the progress bar, there should have been an output that reports how many features were generated, since you were running with `verbose=True`. Can you let me know how many features is says were generated?

Also, to answer your question from above. I have been able to resolve prior memory issues by changing the partition size in the input dataframe as well as changing the number of workers and memory per worker. Unfortunately, the process was a bit of trial-and-error to find the solution. You can try running with a single dask worker `n_workers=1` and allocating all your memory to that worker to see if that helps.

**Comment by gautambak** [comment]
Thanks so much Nate - It took almost 1 hour to start this. It looks like it built 12544 features.

```
Built 12544 features
/usr/local/lib/python3.7/dist-packages/featuretools/synthesis/dfs.py:317: UnusedPrimitiveWarning: Some specified primitives were not used during DFS:
  agg_primitives: ['std', 'sum']
This may be caused by a using a value of max_depth that is too small, not setting interesting values, or it may indicate no compatible variable types for the primitive were found in the data.
  warnings.warn(warning_msg, UnusedPrimitiveWarning)
Elapsed: 01:04 | Progress: 100%|██████████
```

When you say you change the partition size of the inputted dataframe. Would that be when I import the pandas DF into dask? I'm creating 50k partitions to try to make it never exceed memory.

**Comment by thehomebrewnerd** [comment]
Yes, when I was mentioning changing the partition size I was referring to the step where you convert the pandas DF into Dask.

You are generating a large number of features with this call. Essentially you will be creating a feature matrix dataframe that has 5926577 rows and 12544 columns. This feature matrix will be *roughly* 77 times the size of your original dataframe which had 163 columns (12544 / 163 ~= 77). So if you are starting with an 11GB dataframe your feature matrix will be 11GB * 77 or about 850GB!

Is your environment set up to handle output of that size?

**Comment by gautambak** [comment]
Thanks. I didn't realize that. I'm playing around with this is colab. I thought it would save to disk. Oddly I have 250 gb of harddrive space and this didn't take up any space at all. 

This maybe a wrong assumption on my part but I thought by using dask I was using drive space and not memory?  I can always mount a TB drive via google or aws.

**Comment by thehomebrewnerd** [comment]
Yes, it should mostly be swapping to disk as far as I know. Also, my numbers are just estimates and could vary somewhat depending on the dtypes of the columns in the input and output, but it should at least give you some idea what to expect. Regardless, you will need a healthy amount of disk space to save the results.

Is the data you are using proprietary, or is it something you can share? If you can share, I can try to replicate the issue on my end which might help me provide a better solution.

Here are a few things I would try next to troubleshoot:
- Run with only the `add_numeric` transform primitive. (Note, if your EntitySet only has a single Entity, the aggregation primitives are not adding any features - as indicated by the `UnusedPrimitiveWarning`, so you really don't need to specify any aggregation primitives in this case)
- Try to increase/decrease your Dask partition size. Maybe try 100,000 partitions, or even 10,000. I did see some cases where using larger partitions was helpful.
- Use a single Dask worker with 4GB of memory instead of 2 workers with 2GB memory each.

**Comment by gautambak** [comment]
Thanks Nate - it's not fully proprietary, but if it works I can share my screen? or send you a subset of the (privately)?

For my dataset, I prejoin and do some processing on the dataframes so by the time I pass it to featuretools it's only one entity.

I'll try your suggestions and report back. Thank you so much Nate!

**Comment by gautambak** [comment]
I tried your suggested changes Nate - 100k partitions + 1 worker with 4GB memory. After a hour I got the 95% memory warning and it crashed my colab instance.

**Comment by thehomebrewnerd** [comment]
Did you try to run with just a single transform primitive to see if it will run with a smaller number of features?

Also, I'm not sure why you had an issue before with `max_depth=1`. Could you try that again and post the full error stack trace so I can try to figure out why that didn't work?

**Comment by thehomebrewnerd** [comment]
@gautambak I've spent some time today experimenting and looking into this issue and I realized something. With a Dask dataframe input, the feature matrix is returned as a Dask delayed object that still needs to be computed, and the call to `ft.dfs` shouldn't be that memory intensive. With that in mind, I started experimenting and I have a something else for you to try.

In my experiment I created a dataframe with 160 numeric columns and 5.9 million rows, which was about 7.5 GB in size. I converted this dataframe to Dask, using only 100 partitions. I was able to successfully run `ft.dfs` to generate the Dask feature matrix with 25,600 features. I did not try to save this to disk because of the space that would be required. One thing that I found that was necessary was passing in a list of instance ids to the call to DFS.

In your call to `ft.dfs` can you also try including `instance_ids=list(range(len(Main)))`? This should prevent Featuretools from doing a `compute()` call behind the scenes, and that *might* be the source of your memory issues.

I'm including the testing notebook I created for your reference, so you can see how I set things up.

[Dask Memory Testing.ipynb.zip](https://github.com/alteryx/featuretools/files/6200140/Dask.Memory.Testing.ipynb.zip)

**Comment by gautambak** [comment]
WOW! Thank you so much @thehomebrewnerd  Nate!! 

It not only seems to work but before it would run for like 2 hours before starting to build features..now it just starts right away! That's so cool. I'm going to do some more testing(save the file, etc) and report back but it is working now!

You rock!!

**Comment by thehomebrewnerd** [comment]
Glad to hear the `ft.dfs` step is working for you now!

**Comment by gautambak** [comment]
Thank you so much @thehomebrewnerd - it’s so kind of you to take time to look into this for me. I’m still playing with featuretools but this probably is fixed.   Thank you so much !

**Comment by thehomebrewnerd** [comment]
@gautambak No problem. Glad I could help!
