### ISSUE TITLE
Spike: Investigate Woodwork Accessor integration into Featuretools

### ISSUE THREAD

**Issue by gsheni** [alteryx/featuretools#1358]
- This issue will investigate how to put Woodwork typing via DataFrame Accessor into Featuretools
- It will create any additional issues as needed
- It will prioritize the issues in the Backlog. 
- It will investigate if Entity should be fully replaced with DataFrame OR keep Entity (to avoid making a large breaking change).

**Comment by thehomebrewnerd** [comment]
Created 12 new issues as a result of this Spike investigation. All new issues are either in Backlog or Sprint and are roughly organized by order in which they should be completed in order to minimize breaking Featuretools tests.

Completion of the issues identified should allow for a complete replacement of the Featuretools Entity class with a Woodwork dataframe.
