### ISSUE TITLE
EntitySet copy operations do not retain Woodwork typing information

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/featuretools#1362]
Currently running `copy.deepcopy(entityset)` will cause any typing information contained in the Woodwork dataframes in the entityset to be lost. Add `__copy__` and `__deepcopy__` methods to `EntitySet` to make sure that Woodwork typing information is retained properly after copy operation.

Corresponding tests for these methods should also be added.

**Comment by tamargrey** [comment]
@ghseni We need this for the `es` fixture which relies on deep-copying the ecommerce entityset

**Comment by tamargrey** [comment]
Going to get the initial Woodwork-Entity replacement in before implementing this, but we'll want to make sure to use deepcopy in our test fixtures since its quicker than calling `make_ecommerce_entityset`.

![image (3)](https://user-images.githubusercontent.com/64278226/117024518-1161f080-acc8-11eb-8867-1b4c32f4a5ca.png)

Note: We should also make sure to reference `pd_es` in `ks_es` and `dask_es` instead of `make_es` to get this benefit.

**Comment by tamargrey** [comment]
Also worth noting that `deepcopy` of a Woodwork TableSchema will not currently work for koalas while we are storing a Series in the metadata, so we may need to implement #1254 before this.

**Comment by tamargrey** [comment]
So removing last time index from the metadata of a `TableSchema` means that we can now deepcopy the TableSchema for Koalas, but it seems like `copy.deepcopy` of a Koalas DataFrame or Series doesn't work in general. 

It throws the same `TypeError: cannot pickle '_thread.RLock' object` even on an EntitySet with Entity objects in main. We just only use the deepcopy in the `pd_es` and `int_es` fixtures, so that's why it wasn't an issue before, I guess. 

@gsheni Are we okay with just getting deepcopy working on pandas (and maybe also Dask, since that works too)?

**Comment by gsheni** [comment]
> @gsheni Are we okay with just getting deepcopy working on pandas (and maybe also Dask, since that works too)?

@tamargrey yes, that is fine. Let's create an issue to address the Koalas deepcopy later on (Dask as well if needed).

**Comment by tamargrey** [comment]
Created an issue for the koalas EntitySet deepcopy: #1466
