### ISSUE TITLE
Test validation in EntitySet.update_data

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/featuretools#1368]
We should improve the validation that occurs when updating data using the EntitySet.update_data method. Currently users can update the data with a new dataframe that has incompatible dtypes, for example changing a column from an int64 column to a string column, but the Variable type retains the Numeric type. This can create issues downstream when computing features.

As part of the Woodwork integration, we should require that the new data conform to the schema of the existing data. The incoming data doesn't necessarily have to match as it is passed in, especially if users supply a dataframe without Woodwork initialized, but Featuretools should be able to update the LogicalTypes and dtypes of the incoming data to match the original schema.

**Comment by tamargrey** [comment]
I _think_ this is currently being done in `update_dataframe`. 

The current implementation will allow for a dataframe being passed in that has dtypes that do not match the woodwork schema or even has data that needs to be transformed (latlongs, for example), because we call `LogicalType.transform` on every column before initializing Woodwork with `df.ww.init(schema=schema)`.

If any data cannot be transformed to match the TableSchema, `update_dataframe` will raise a `TypeConversionError`.

**Comment by thehomebrewnerd** [comment]
I agree that is seems this is being done based on the current code. Based on a quick search I'm not seeing a test where we specifically test this situation though. Maybe we should add one that does this with a couple columns (latlong would be a good one to include) just to make sure we have this covered in the future?

I think that should be a relatively simple add and then we can close this out.

**Comment by thehomebrewnerd** [comment]
Upon further review this behavior mentioned in this issue is covered by two different existing tests in `entityset/test_ww.es.py`:
- `test_update_dataframe_different_dtypes`
- `test_update_dataframe_data_transformation`

Based on that, this issue can be closed without implementing any changes.
