### ISSUE TITLE
Handle divide by 0 in DivideNumeric primitives

### ISSUE THREAD

**Issue by gsheni** [alteryx/featuretools#1496]
- The Binary Transform Primitive in Featuretools which will divide 2 numeric columns
- However, this primitives does not currently handle divide by 0 (it outputs **inf**, when it should output **NaN**)
- The DivideNumeric primitives should handle the divide by 0 case and output NaN, not `inf` like it currently does.
  - Ideally this happens without significantly affecting primitive performance speed 

### Open Questions
- Does this apply to DivideNumericScalar and DivideByFeature too?

**Comment by thehomebrewnerd** [comment]
After investigation, the primitive is performing as expected based on the divide-by-zero approach implemented in numpy, which is consistent with IEEE754.

An alternate solution to this issue has been proposed to allow removal of `inf` values prior to downstream ML processing. Rather than updating the primitive output directly, Featuretools will add a new function to replace `inf` values in a feature matrix with `nan` or with another value specified by the user.
