### ISSUE TITLE
Add Expanding* primitives for time series feature engineering

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/featuretools#2242]
Add `Expanding*` versions of the `Rolling*` primitives for time series feature engineering. 

The current rolling primitives, such as rolling max, use data contained within a window to determine the value along with a gap, which allows them to be used to create features from a target column without including recent values. We could add corresponding `Expanding*` primitives that include a gap parameter that uses all of the previous history excluding the gap rows to calculate the values. This could be implemented as new primitives or by including an optional gap parameter in the existing `Cumulative*` primitives or by updating the `Rolling*` primitives to use all history prior to the gap rows. The fact that the current `Cumulative*` primitives do not have a gap option prevents them from being used to create time series features from a target column as they would leak the target value at each time step. Similarly, since the current `Rolling*` primitives don't have an option to use all history they cannot be used for this purpose.

See technique 5 in this article for more info: https://www.analyticsvidhya.com/blog/2019/12/6-powerful-feature-engineering-techniques-time-series/

**Comment by sbadithe** [comment]
Regarding the placement of the primitives, I was thinking this might be a desirable end-state for the directory structure: 
```
/time_series

    /expanding 
    /exponential 
    /rolling 
```
I'm a fan of making the new expanding primitives live in their folder, instead of adding a parameter to the rolling or cumulative primitives. Here are some of my thoughts: 

Pros:
- The rolling primitives are already pretty complex -- they have huge docstrings and many knobs to turn. Adding another parameter would result in a corresponding increase in complexity, both for us as devs and also for users navigating the docstring and trying to reason about the primitives, perhaps for the first time.
- Testing the rolling primitives is already pretty complicated. We parametrize on `window_length`, `gap`, and `min_periods`. If we choose to parametrize on `rolling` vs `expanding`, this might make the tests even harder to reason about.
- We would be mirroring the Pandas layout, which has exponential, expanding, and rolling all listed under the windows umbrella.
- It would be really easy to see what’s implemented and what is not. We would just need to compare the rolling folder and expanding folder. For example, if we combine implementations, and we accidentally forget to define an expanding version of a rolling primitive, it might be nontrivial to catch this.


Cons:
- We would have some duplicated core logic, i.e. a `RollingMean` and a `ExpandingMean`. This would mean, in the worst case, 2x the number of files. I think this only becomes an issue if we have a huge amount of primitives, at which point we could explore refactoring. Moreover keeping them separate would reinforce that they are logically very different in terms of results. 

Regarding repurposing the cumulative primitives, I think it would be nice to keep them outside. This would emphasize the idea that time series primitives are distinct from the other 'classical' ones.

Curious to hear your thoughts! @thehomebrewnerd @gsheni

**Comment by thehomebrewnerd** [comment]
@sbadithe In my opinion these should be separate primitives that reside in their own files, as you suggest. Overall I think it is better if we can implement simple primitives that stand on their own and not create complicated primitives with a lot of parameters.

If there is common logic shared among the primitives, it's possible we can handle this in a couple different ways. One way would be to move the common logic into utility functions and then import and use that in each individual primitive implementation. Another approach might be use us a base class that can be extended by the individual implementations. I haven't studied the details here, so I'm not sure which of those would make the most sense in this case.

**Comment by gsheni** [comment]
We shouldn't separate out primitives by the problem type. Primitives are general operations that can be applied to any dataset (time series happens to be a situation where these primitives are highly recommend).

**Comment by thehomebrewnerd** [comment]
> We shouldn't separate out primitives by the problem type. Primitives are general operations that can be applied to any dataset (time series happens to be a situation where these primitives are highly recommend).

@gsheni We already did that in my restructuring MR.

**Comment by gsheni** [comment]
Gotcha. My point was there should not be a folder called `regression`, `classification`, and `time_series`. 
I think we should have named the folder something else, but it's okay for now. We may find that those primitives are still useful (if you have a time_index + regression/classification problem).

**Comment by thehomebrewnerd** [comment]
> Gotcha. My point was there should not be a folder called `regression`, `classification`, and `time_series`. I think we should have named the folder something else, but it's okay for now. We may find that those primitives are still useful (if you have a time_index + regression/classification problem).

Yeah, that's a fair point. I was originally thinking they would only apply to time series problems, but they might have use more broadly, in which case we would want to update the folder structure.

**Comment by sbadithe** [comment]
We can rename the folder to `windowing` or `window`.

**Comment by gsheni** [comment]
@sbadithe are we sure these Expanding primitives are not the same as CumX primitives or Rolling primitives?

  > Rolling will take into account a fixed width window of the previous n values, while expanding takes into account all previous values in scope. https://stackoverflow.com/questions/58115568/what-are-pandas-rolling-and-expanding-doing
- That convinces me that its not the same as Rolling primitives

However with regard to CumlativeX primitives:
> They are basically the same, but you will get NaNs with expanding_sum until you reach the required minimum number of observations. https://stackoverflow.com/questions/32911939/pandas-series-cumsum-vs-pandas-expanding-sum

**Comment by thehomebrewnerd** [comment]
@gsheni The primitives are similar, but I think there are a couple key differences between CumulativeX and ExpandingX primitives:
- The cumulative primitives use all the data all the time. The ExpandingX primitives should only go back `N` rows in time so we can properly configure a time series problem, let's say we want to predict the next 7 days of sales using only the previous 30 days, but our dataset contains more than 30 days of history. My expectation is that the expanding primitives will respect this setup and not go back further than 30 days, while the current cumulative primitives will always use all the data
- The expanding primitives should have a configurable gap, which allows us to account for data availability delays common in time series problems. The current cumulative primitives do not have this capability.
