### ISSUE TITLE
Deprecate support for Spark DataFrames

### ISSUE THREAD

**Issue by gsheni** [alteryx/featuretools#2557]
We would like to remove Spark support from Featuretools.
If you are using Spark DataFrames in Featuretools, please leave a comment

**Comment by vishalovercome** [comment]
This looks like a major decision, especially in light of your documentation:

`Support for Spark EntitySets is still in Beta. While the key functionality has been implemented, development is ongoing to add the remaining functionality.`

This had led me to believe that Spark support would be enhanced but you're looking to remove Spark support all together. Can you explain the reason for this change in direction? 

I was about to use featuretools inside my organization as this looks like a very very useful project. As we build models over a large dataset distributed data processing is a must. Is Dask + featuretools the only option then?

**Comment by gsheni** [comment]
hi @vishalovercome, we would like to remove Spark for the following reasons:
- The release cycle for Spark is very slow. They do not release regularly and sometimes it can be a few months.
- Python 3.11 has been out for a while now but we had to hold up on that support (on Featuretools) because PySpark doesn't support it

Can you describe how you are using Spark DataFrames? How well does it work for you (speed, runtime improvements)? Would you be open to using Dask DataFrames instead?

**Comment by vishalovercome** [comment]
Thanks for your prompt response! As mentioned earlier, I'm still exploring featuretools and seeing the wealth of features that it provides, especially when used along with tsfresh makes it a must have. We do have several machine learning projects that are built using pyspark and would greatly benefit from featuretools as well.

Your argument for dropping Spark support doesn't seem strong. featuretools is a relatively recent library used by professional who are working on the bleeding edge of ML. Spark is a data processing framework that has been around for over a decade and hence cannot move as fast. The framework itself is written using Java/Scala which are even slower to release newer iterations because languages are used for wide variety of reasons. No matter what the ecosystem, a library will always move faster than a framework which itself will move faster than a language. 

That shouldn't stop you from upgrading to Python 3.11. You should go ahead and do that and perhaps deprecate support for some older versions of Python as well. It will then be upto Spark users to decide whether to switch frameworks and upgrade featuretools or just stick with an older version of it. Having a working package is better than not having it at all.

I can also see that [PySpark 3.4.0](https://pypi.org/project/pyspark/) comes with support for Python 3.11. 

Finally, I don't know how you've implemented Spark support but if you're leveraging Pandas API on Spark then I would imagine that slowness of Spark ecosystem wouldn't be that big of a problem.

**Comment by chouligi** [comment]
To me one of the main advantages of featuretools (and disadvantage of competing frameworks) is the ability to support Spark (at least in Beta), since most real life ML use cases need data that do not fit in pandas dataframes. I was looking forward to further support for Spark so quite disappointing to see it is dropped. It would be great to see it further developed.

**Comment by gsheni** [comment]
Due to the community feedback, we have decided not to remove Spark support in Featuretools.
